# Generated by Django 4.1.6 on 2023-04-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ANYWHEREEVERYWHERE', '0004_alter_rating_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
